// Google Apps Script — rekap Pretest & Post-test Pekan 4 Day 2 · Decision Tree ke Google Sheet
// Kunci & pembahasan disimpan di sini (bukan di HTML).
// Pretest: peserta hanya menerima skor. Post-test: peserta menerima skor + kunci + pembahasan.
// Versi bank soal. Halaman tes hanya menampilkan skor bila versi ini cocok dengan VER di HTML.
const VER = "p4d2-1";

// Awalan nama sheet, supaya beberapa hari bisa disalin ke satu spreadsheet tanpa bentrok nama.
const PREFIX = "P4D2 ";

// Soal Pekan 4 Day 2 · Decision Tree — pretest dan post-test memakai soal & kunci yang sama.
const KEY = "DBEACECADBADBEC".split("");

// Pembahasan per nomor (HTML).
const EXPL = [
    "<p>Pruning memangkas cabang dari tree yang lebih besar. Tujuannya mengendalikan kompleksitas agar pola yang dipelajari lebih mungkin bertahan pada data baru. Tree besar dapat menyesuaikan noise dan kekhususan training; training error yang rendah belum membuktikan generalisasi yang baik.</p><p>Cross validation menilai kandidat pada bagian data yang ditahan dari pelatihan setiap fold. Pada soal, A dan B sudah dinyatakan memenuhi aturan 1 SE. Karena tujuan yang ditetapkan adalah memilih kandidat paling sederhana yang masih kompetitif, A menjadi pilihan. Ini tidak berarti A pasti lebih akurat daripada B pada setiap dataset baru.</p><p>Pada subtree hasil pemangkasan, training error umumnya tetap atau memburuk, sedangkan error validasi dapat membaik. Cross validation membantu menentukan kompromi tersebut. Setelah pilihan dikunci, test set dipakai untuk evaluasi final.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Training error terendah dapat berasal dari overfitting. Cross validation juga digunakan untuk memilih kompleksitas tree, bukan hanya threshold.</p><p class=\"ox\"><b>B</b> B sesuai aturan minimum galat validasi, tetapi tujuan soal memakai aturan 1 SE yang mengizinkan kandidat lebih sederhana.</p><p class=\"ox\"><b>C</b> Pilihan A tepat, tetapi alasannya salah: pruning tidak bertujuan menurunkan training error dan tidak menjamin keduanya membaik.</p><p class=\"ox\"><b>D</b> Benar. Keputusan mengikuti aturan yang ditetapkan dan menggunakan validasi untuk menilai manfaat kompleksitas.</p><p class=\"ox\"><b>E</b> Memilih kandidat dengan test lalu menilai pada test yang sama membuat evaluasi akhir ikut terlibat dalam tuning.</p>",
    "<p>Satu jalur dari root ke daun dibaca sebagai konjungsi: semua syarat pada jalur tersebut harus terpenuhi, sehingga dihubungkan dengan DAN. Beberapa daun yang dipilih digabungkan dengan ATAU. Syarat root tetap harus dibawa ke aturan daun.</p><p>Pada cabang kiri root, mobil < 4,5 berarti mobil ≤ 4. Daun Yes berada pada cabang kanan node daya < 6,5, sehingga daya ≥ 7. Pada cabang kanan root, mobil ≥ 4,5 berarti mobil ≥ 5. Daun Yes berada pada cabang kiri node kebakaran < 3,5, sehingga kebakaran ≤ 3.</p><p>Contoh pemeriksaan: pelanggan dengan mobil = 4 dan daya = 7 masuk Yes berapa pun nilai kebakarannya. Pelanggan dengan mobil = 5 dan kebakaran = 4 masuk No berapa pun nilai dayanya. Kode kategori ini tidak otomatis merupakan nilai rupiah atau hubungan sebab akibat.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Cabang Yes pada sisi kanan root menggunakan kebakaran < 3,5, bukan kebakaran ≥ 3,5.</p><p class=\"ox\"><b>B</b> Benar. Kedua jalur Yes lengkap, batas integer tepat, dan dua segmen digabung dengan ATAU.</p><p class=\"ox\"><b>C</b> Menukar prediktor antar-subtree mengubah segmentasi; daya hanya diuji di kiri root dan kebakaran hanya di kanan.</p><p class=\"ox\"><b>D</b> Syarat mobil ≤ 4 dan mobil ≥ 5 tidak dapat terpenuhi sekaligus. Penggabungan antar-daun harus ATAU.</p><p class=\"ox\"><b>E</b> Daya = 6 dan kebakaran = 4 salah dimasukkan ke Yes. Batas integer harus mengikuti ketaksamaan asli.</p>",
    "<p>Root adalah titik awal pembagian data. Internal node menerapkan pengujian untuk menentukan cabang berikutnya. Daun atau terminal node memberikan keluaran akhir untuk observasi yang mencapai node tersebut. Sebuah node dapat menjadi anak dari node lain sekaligus menjadi internal node bila masih mempunyai anak.</p><p>Ketika subtree di bawah node 7 dipangkas, aturan sepanjang root sampai node 7 tetap menentukan siapa yang masuk ke segmen tersebut. Namun, pembedaan tambahan yang sebelumnya mengarahkan observasi ke 14 atau 15 hilang. Node 7 menjadi satu daun dengan keluaran terminalnya sendiri.</p><p>Pruning mengubah struktur keputusan, bukan menghapus observasi atau otomatis membuang kolom prediktor dari dataset. Variabel pada split yang dihapus masih dapat digunakan pada bagian tree lain. Variabel root juga tidak otomatis memiliki variable importance total tertinggi, karena importance dapat menggabungkan kontribusi dari beberapa split.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Root adalah split pertama, tetapi tidak otomatis peringkat importance total tertinggi. Prediksi tetap tersedia pada daun pengganti.</p><p class=\"ox\"><b>B</b> Pruning tidak mengalihkan observasi ke saudara node. Pelanggan tetap mengikuti jalur yang menuju node 7.</p><p class=\"ox\"><b>C</b> Daun adalah hasil akhir jalur. Menghapus split tidak sama dengan menghapus prediktor dari dataset atau semua subtree.</p><p class=\"ox\"><b>D</b> Posisi di bawah node lain tidak menjadikan sebuah node terminal. Sebelum dipangkas, node 7 masih bercabang.</p><p class=\"ox\"><b>E</b> Benar. Identitas internal node, perubahan menjadi daun, dan penyederhanaan aturan dijelaskan dengan tepat.</p>",
    "<p>maxdepth adalah batas atas kedalaman, bukan target yang wajib dicapai. Menaikkannya membuka kemungkinan jalur yang lebih panjang, tetapi tidak memerintahkan tree untuk menambah percabangan. Root dihitung pada depth 0; kedalaman menunjukkan panjang jalur, bukan jumlah prediktor unik atau jumlah seluruh daun.</p><p>Batas pertumbuhan bekerja bersama. Tree masih dapat berhenti karena node terlalu kecil untuk dicoba di-split, kandidat menghasilkan anak yang terlalu kecil, atau perbaikannya tidak memenuhi batas cp. Dengan demikian, hasil yang tetap dangkal tidak otomatis menunjukkan parameter diabaikan.</p><p>Jika batas kedalaman semula benar-benar menghalangi split yang memenuhi syarat lain, menaikkannya dapat menghasilkan tree lebih rinci. Hal itu dapat membantu menangkap pola, tetapi juga memberi ruang untuk mempelajari noise. Pilihan parameter tetap dinilai dengan validasi, bukan hanya dari besar atau kecilnya tree.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Benar. Membedakan batas maksimum dari target pertumbuhan dan mempertimbangkan syarat penghentian lain.</p><p class=\"ox\"><b>B</b> Kedalaman tidak wajib mencapai batas. cp yang lebih besar justru memperketat kebutuhan perbaikan untuk pertumbuhan.</p><p class=\"ox\"><b>C</b> maxdepth membatasi kedalaman jalur. Ia bukan batas jumlah variabel; prediktor dapat digunakan kembali pada node lain bila sesuai.</p><p class=\"ox\"><b>D</b> maxdepth membatasi pertumbuhan tree saat fitting, bukan hanya setelah pruning.</p><p class=\"ox\"><b>E</b> Tree yang sama menunjukkan perubahan batas itu belum mengubah hasil pada kondisi ini. Hal tersebut tidak membuktikan optimalitas pada data baru.</p>",
    "<p>minbucket paling langsung menjawab kebutuhan ukuran minimum daun. Batas yang lebih besar membuat split yang menghasilkan anak terlalu kecil tidak memenuhi syarat. Ini membantu menghindari segmen yang hanya ditopang sedikit observasi, meskipun tidak menjamin semua segmen menjadi stabil pada setiap sampel.</p><p>minsplit mengatur apakah sebuah node cukup besar untuk dicoba di-split. Node parent yang besar masih dapat dibagi menjadi anak yang tidak seimbang ukurannya. Karena itu, menaikkan minsplit saja tidak menetapkan batas ukuran daun yang sama dengan nilai minsplit tersebut.</p><p>Batas ukuran daun yang terlalu besar juga punya konsekuensi: kelompok kecil dengan pola yang sebenarnya berguna dapat digabung dengan kelompok lain. Pilih batas melalui validasi serta kebutuhan keterbacaan dan kestabilan segmen. Dalam rpart, bila hanya minsplit atau minbucket diberikan, nilai pasangannya dapat diturunkan otomatis; soal sengaja menetapkan keduanya secara eksplisit.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> minsplit membatasi ukuran parent sebelum percobaan split, bukan ukuran minimum setiap daun hasilnya.</p><p class=\"ox\"><b>B</b> Tree dangkal tetap bisa mempunyai daun kecil. maxdepth tidak menjamin minimum jumlah observasi per daun.</p><p class=\"ox\"><b>C</b> Benar. Parameter sesuai tujuan, arah perubahan tepat, dan konsekuensi terhadap pola langka diakui.</p><p class=\"ox\"><b>D</b> Menurunkan minbucket justru mengizinkan daun yang lebih kecil. Menaikkan minsplit tidak membatalkan kelonggaran itu pada ukuran daun.</p><p class=\"ox\"><b>E</b> xval mengatur cross validation, bukan batas ukuran daun. Menambah fold tidak otomatis mengubah minbucket.</p>",
    "<p>Test set harus mewakili distribusi penggunaan yang dituju dan tetap terpisah dari proses pemilihan konfigurasi. Stratifikasi membantu mempertahankan proporsi kelas, tetapi tidak memperbaiki kebocoran akibat duplikasi observasi atau penggunaan test untuk tuning.</p><p>Pada setiap fold validasi internal, oversampling hanya boleh menggunakan bagian training fold tersebut. Fold validasi dipertahankan pada distribusi asli. Prediksi validasi internal dapat digunakan untuk memilih CP serta aturan threshold atau top 20%. Sesudah keputusan dikunci, model dilatih ulang menggunakan seluruh training dengan prosedur yang terpilih.</p><p>Gunakan test set yang sama untuk perbandingan yang lebih adil. Jika test kemudian dipakai memilih pemenang untuk deployment, angka pemenang dapat mengandung bias seleksi; validasi eksternal atau pilot baru akan memperkuat klaim performa. Protokol E paling memenuhi tujuan evaluasi final yang dinyatakan.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Duplikasi hasil oversampling dapat masuk train dan test; distribusi test juga tidak lagi mencerminkan prevalensi asli.</p><p class=\"ox\"><b>B</b> Duplikat yang dibuat sebelum CV dapat tersebar ke fold training dan fold validasi, sehingga estimasi CV terlalu optimistis.</p><p class=\"ox\"><b>C</b> Test ikut menentukan threshold. Hasil pada data yang sama bukan evaluasi final independen dari pemilihan konfigurasi.</p><p class=\"ox\"><b>D</b> Perbedaan hasil bercampur dengan perbedaan komposisi test. Gunakan pembagian yang sama untuk perbandingan yang dikendalikan.</p><p class=\"ox\"><b>E</b> Benar. Pemisahan data, lokasi sampling, pemilihan konfigurasi, dan evaluasi final sesuai tujuan.</p>",
    "<p>Konfigurasi B menurunkan cp, minsplit, dan minbucket serta menaikkan maxdepth. Gabungan perubahan ini melonggarkan kesempatan pertumbuhan: split dengan perbaikan lebih kecil dapat dipertimbangkan, node lebih kecil boleh dicoba di-split, daun lebih kecil diizinkan, dan jalur dapat menjadi lebih dalam.</p><p>Batas yang lebih longgar tidak menjamin tree aktual selalu bertambah besar; pertumbuhan tetap bergantung pada data dan split yang tersedia. Jika tree menjadi lebih rinci, kecocokan training dapat membaik tetapi risiko mempelajari noise juga meningkat. Performa validasi dapat membaik, tetap, atau memburuk.</p><p>minsplit mengatur ukuran minimum node sebelum percobaan split, sedangkan minbucket mengatur batas ukuran terminal node. xval meminta cross validation untuk estimasi kinerja pada tabel kompleksitas. Pengguna tetap perlu memilih kompleksitas dan melakukan pruning sesuai aturan yang ditetapkan.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Melonggarkan batas dapat membantu menangkap pola, tetapi juga meningkatkan peluang overfitting. Validasi tidak dijamin membaik.</p><p class=\"ox\"><b>B</b> cp yang lebih kecil melonggarkan batas perbaikan, bukan memperketatnya.</p><p class=\"ox\"><b>C</b> Benar. Menjelaskan arah perubahan parameter tanpa menjanjikan perbaikan validasi, serta membedakan CV dari pruning final.</p><p class=\"ox\"><b>D</b> Definisi minsplit dan minbucket tertukar. Kekeliruan ini dapat menghasilkan konfigurasi yang tidak sesuai tujuan.</p><p class=\"ox\"><b>E</b> Jumlah fold yang sama tidak berarti hasil tree sama atau pruning final otomatis dilakukan.</p>",
    "<p>Urutan faktor adalah c(\"Yes\", \"No\"), sehingga elemen pertama prior merujuk Yes. Matriks hasil kode adalah baris Yes: [0, 1] dan baris No: [6, 0]. Sel di luar diagonal menunjukkan biaya kesalahan, sedangkan diagonal nol berarti tidak ada biaya klasifikasi benar.</p><p>Dengan Yes sebagai kelas positif, false negative adalah aktual Yes tetapi diprediksi No, yaitu loss[1, 2] = 1. False positive adalah aktual No tetapi diprediksi Yes, yaitu loss[2, 1] = 6. Jangan mengasumsikan urutan No, Yes ketika level sudah diubah eksplisit.</p><p>Prior mengubah asumsi frekuensi kelas dalam pemodelan; ia bukan instruksi random oversampling atau undersampling. Prior Yes yang besar dan biaya false positive yang besar memberi dorongan berbeda. Prediksi akhir tetap bergantung pada distribusi data, prior, loss, dan struktur tree, sehingga tidak dapat disimpulkan semua daun menjadi Yes.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Benar. Urutan prior, orientasi loss, jenis kesalahan, dan pembedaan dari resampling tepat.</p><p class=\"ox\"><b>B</b> Level eksplisit mengalahkan urutan alfabet. Prior dan biaya yang disebutkan menjadi tertukar.</p><p class=\"ox\"><b>C</b> Orientasi matriks terbalik. Soal menetapkan baris aktual dan kolom prediksi.</p><p class=\"ox\"><b>D</b> Penafsiran prior dan biaya benar, tetapi prior tidak menduplikasi atau membuang baris data.</p><p class=\"ox\"><b>E</b> Prior dominan tidak menjamin semua prediksi Yes; loss dan bukti pada masing-masing node tetap berperan.</p>",
    "<p>Precision menjawab: di antara pelanggan yang diprediksi Yes, seberapa banyak yang benar-benar Yes? Ketika Yes makin jarang, jumlah pelanggan No yang berpotensi menjadi false positive jauh lebih besar. Maka alert positif dapat mempunyai precision lebih rendah walaupun kemampuan mengenali masing-masing kelas tidak berubah.</p><p>Dengan distribusi skor bersyarat kelas dan threshold tetap, sensitivity serta specificity tetap sesuai asumsi soal. Kurva ROC populasi dan AUC juga tidak otomatis berubah hanya karena prevalensi berubah. Sebaliknya, precision dan accuracy dapat berubah. Pada sampel terbatas, hasil estimasi tetap dapat berfluktuasi.</p><p>Evaluasi pada data seimbang berguna untuk tujuan tertentu, tetapi precision-nya tidak boleh langsung dianggap sebagai tingkat keberhasilan kontak pada populasi asli. Untuk keputusan operasional, gunakan validasi representatif dan baca precision atau kurva precision-recall bersama ukuran lain yang sesuai tujuan.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Recall dinilai terhadap kelas aktual Yes, bukan seluruh pelanggan. Prevalensi bukan penyebut langsung recall.</p><p class=\"ox\"><b>B</b> Lebih sedikit prediksi Yes tidak menjamin precision lebih tinggi. Accuracy masih dapat menjadi pendamping, tetapi tidak cukup digunakan sendiri.</p><p class=\"ox\"><b>C</b> Precision dapat turun tanpa ROC populasi berubah di bawah asumsi yang diberikan. Keduanya menjawab pertanyaan berbeda.</p><p class=\"ox\"><b>D</b> Benar. Mengaitkan base rate dengan keberhasilan alert sambil menghormati asumsi kestabilan sensitivity dan specificity.</p><p class=\"ox\"><b>E</b> Threshold dan AUC yang sama tidak menjamin precision yang sama. Kelas positif mengikuti tujuan analisis, bukan kelas mayoritas.</p>",
    "<p>Proporsi kelas mentah dan skor model dengan prior buatan menjawab hal yang berbeda. Proporsi 20% merangkum komposisi training pada daun tersebut. Skor sekitar 80% dipengaruhi asumsi prior dalam pemodelan. Skor itu tidak otomatis menjadi peluang pembelian yang terkalibrasi pada populasi dengan prevalensi asli.</p><p>Proporsi training juga bukan jaminan peluang populasi baru. Daun dibentuk dengan menggunakan data training sehingga dapat menangkap pola yang terlalu spesifik. Gunakan validasi representatif untuk memeriksa keberhasilan segmen dan kalibrasi ketika skor hendak ditafsirkan sebagai probabilitas atau dipakai menghitung nilai keputusan.</p><p>Prediksi pembelian tidak sama dengan efek kontak pemasaran. Pelanggan berpeluang beli tinggi mungkin tetap akan membeli tanpa dihubungi. Untuk mengetahui dampak tambahan kontak, diperlukan rancangan yang mendukung inferensi kausal, misalnya eksperimen kontak dan kelompok pembanding.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Prior seimbang tidak otomatis mengkalibrasi peluang ke populasi asli; klaim efek kontak juga tidak diidentifikasi oleh tree ini.</p><p class=\"ox\"><b>B</b> Benar. Membedakan komposisi data, skor model, validasi populasi, dan efek intervensi.</p><p class=\"ox\"><b>C</b> Prior global bukan nilai yang harus sama di setiap daun. Informasi prediktor tetap membedakan peluang antarsegmen.</p><p class=\"ox\"><b>D</b> Interpretabilitas tidak menjamin kalibrasi atau validitas kausal. Keuntungan kontak memerlukan informasi manfaat dan biaya yang sesuai.</p><p class=\"ox\"><b>E</b> Frekuensi training tetap memerlukan validasi karena pemilihan segmen dan pergeseran populasi dapat membuatnya terlalu optimistis.</p>",
    "<p>cp berperan saat fitting dengan membatasi pertumbuhan yang dinilai tidak cukup memberi perbaikan. Nilai awal yang lebih besar lebih ketat dan dapat membuat cabang tertentu tidak pernah dibangun. Jika objek awal tidak menyimpan cabang tersebut, prune tidak mempunyai cabang baru untuk dipulihkan.</p><p>prune memilih subtree dari tree yang diberikan: ia mempertahankan atau membuang cabang yang ada, bukan menjalankan proses pertumbuhan baru. Memakai cp yang lebih kecil pada prune dapat mempertahankan lebih banyak cabang yang tersedia, tetapi tidak memperluas tree melampaui objek asal.</p><p>Untuk mengeksplorasi segmentasi lebih rinci, ulangi fitting dengan cp awal yang lebih kecil dan kontrol lain yang sesuai. Setelah itu, bandingkan kompleksitas memakai validasi training, tentukan pilihan, dan evaluasi final pada test yang belum dipakai untuk tuning. cp berbeda dari threshold probabilitas: threshold mengubah keputusan kelas dari skor, bukan menambah percabangan.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Benar. Membedakan pertumbuhan dan pemangkasan serta menempatkan validasi sebagai dasar pemilihan kompleksitas.</p><p class=\"ox\"><b>B</b> Jumlah fold tidak mengubah prune menjadi algoritma pertumbuhan. Cabang yang tidak ada tidak dapat dibuat melalui pruning.</p><p class=\"ox\"><b>C</b> cp bukan threshold probabilitas. Mengubah aturan skor menjadi kelas tidak menumbuhkan struktur tree.</p><p class=\"ox\"><b>D</b> cp awal yang lebih besar memperketat pertumbuhan, bukan membuka lebih banyak cabang untuk segmentasi.</p><p class=\"ox\"><b>E</b> cp kecil membuka ruang bagi tree lebih kompleks, tetapi tidak membuktikan kompleksitas tersebut optimal untuk generalisasi.</p>",
    "<p>Recall menjelaskan seberapa banyak kasus aktual Yes yang berhasil ditemukan. Angka recall yang sudah disediakan pada soal menunjukkan bahwa model masih melewatkan banyak kasus positif. Accuracy tinggi tidak menghapus masalah itu, terutama karena No merupakan kelas mayoritas.</p><p>Precision menjawab pertanyaan berbeda: ketika model mengeluarkan alert Yes, seberapa sering alert tersebut benar? Model ini dapat menghasilkan alert yang cukup terarah sekaligus gagal menemukan sebagian besar kasus positif. Kedua kondisi dapat terjadi bersama dan bukan kontradiksi.</p><p>Menurunkan threshold biasanya memperluas prediksi Yes pada skor yang tetap, sehingga recall tidak menurun tetapi false positive dan beban pemeriksaan dapat meningkat. Precision tidak dijamin membaik. Pilih aturan keputusan menggunakan validasi dengan memperhatikan kapasitas, biaya kasus terlewat, dan biaya alert salah.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Definisi precision dan recall tertukar. Precision tidak menyatakan berapa banyak seluruh kasus Yes yang ditemukan.</p><p class=\"ox\"><b>B</b> Accuracy dan precision memakai dasar penilaian yang berbeda. Tidak ada keharusan nilainya mendekati sama.</p><p class=\"ox\"><b>C</b> Mengalahkan baseline pada accuracy tidak berarti tujuan recall sudah tercapai. Tujuan harus dinilai dengan ukuran yang relevan.</p><p class=\"ox\"><b>D</b> Benar. Membaca tiap ukuran sesuai maknanya dan menghubungkan perbaikan deteksi dengan kendala operasional.</p><p class=\"ox\"><b>E</b> Perbaikan recall dapat menambah false positive dan melampaui kapasitas. Threshold perlu divalidasi terhadap seluruh batas keputusan.</p>",
    "<p>Fitur harus tersedia pada waktu keputusan dibuat. Status sengketa akhir mengandung informasi dari masa setelah alert yang ingin diprediksi. Jika informasi itu dipakai saat training dan juga tersedia pada random test dari data historis, evaluasi dapat terlihat sangat baik meskipun prosedurnya tidak dapat diterapkan secara prospektif.</p><p>Pruning, threshold konservatif, dan imputasi nilai yang belum ada tidak menghilangkan masalah mendasar tersebut. Bangun fitur dari informasi yang benar-benar tersedia sebelum alert, lalu latih dan validasi ulang. Gunakan pemisahan waktu atau kelompok yang sesuai apabila ada hubungan temporal atau transaksi berulang dari entitas yang sama.</p><p>Aturan daun dapat menjelaskan kombinasi karakteristik yang terkait dengan risiko fraud dan membantu menentukan prioritas pemeriksaan. Tetapi probabilitas tinggi bukan kepastian fraud. Hasil pemeriksaan, bukti tambahan, kapasitas, dan biaya kesalahan tetap menjadi bagian dari keputusan operasional.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Test historis dapat mengandung kebocoran informasi yang sama dengan training. AUC tinggi tidak memperbaiki ketidaktersediaan fitur saat alert.</p><p class=\"ox\"><b>B</b> Benar. Memperbaiki waktu ketersediaan fitur, mengulangi evaluasi yang sesuai, dan menempatkan tree sebagai alat triase.</p><p class=\"ox\"><b>C</b> Pruning mengurangi kompleksitas, bukan memindahkan waktu tersedianya informasi. Kebocoran dapat tetap ada pada tree sangat sederhana.</p><p class=\"ox\"><b>D</b> Imputasi menciptakan kondisi input berbeda dari evaluasi historis. AUC lama tidak membuktikan performa pada kondisi penggunaan tersebut.</p><p class=\"ox\"><b>E</b> Loss mengatur konsekuensi kesalahan, bukan menggantikan prediktor. Perubahan desain perlu pemodelan ulang, dan skor bukan bukti fraud terkonfirmasi.</p>",
    "<p>ROC memperlihatkan perubahan sensitivity dan false positive rate ketika threshold diubah. Pada grafik dengan sumbu specificity, semakin tinggi specificity berarti semakin kecil proporsi kelas negatif yang salah diberi alert. Sensitivity yang lebih tinggi berarti lebih banyak kasus positif berhasil ditemukan.</p><p>Tujuan soal dibatasi pada wilayah operasional tertentu. M2 memberi sensitivity lebih tinggi pada wilayah yang diizinkan dan mencapai hasil terbaiknya pada batas tersebut. Karena itu M2 lebih sesuai untuk tujuan ini, walaupun M1 mempunyai AUC keseluruhan lebih tinggi.</p><p>AUC merangkum kemampuan pemeringkatan sepanjang seluruh rentang threshold, termasuk wilayah yang tidak diizinkan dalam soal. Kurva yang berpotongan memungkinkan pemenang global berbeda dari pemenang lokal. AUC juga bukan accuracy, bukan probabilitas bahwa setiap alert benar, dan tidak menetapkan satu threshold optimal untuk semua tujuan.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> AUC lebih tinggi tidak berarti ROC mendominasi pada setiap titik. Kedua kurva menggunakan skala yang sama.</p><p class=\"ox\"><b>B</b> Batas operasional tetap harus dipenuhi. Titik dengan sensitivity tinggi bisa tidak layak karena terlalu banyak false positive.</p><p class=\"ox\"><b>C</b> Pilihan M2 tepat tetapi alasannya salah. Specificity menilai pengenalan kelas negatif, sedangkan deteksi positif dinilai oleh sensitivity.</p><p class=\"ox\"><b>D</b> AUC bukan accuracy pada satu threshold. Penggunaan model harus mempertimbangkan wilayah operasi yang relevan.</p><p class=\"ox\"><b>E</b> Benar. Membaca keunggulan lokal berdasarkan tujuan dan batas keputusan, tanpa menyamakan AUC dengan seluruh kinerja operasional.</p>",
    "<p>predict(..., type = \"prob\")[, \"Yes\"] mengambil skor kelas positif. Untuk levels = c(\"No\", \"Yes\"), direction = \"<\" menyatakan kontrol No diharapkan mempunyai skor lebih rendah daripada kasus Yes. ROC/AUC mengevaluasi pemeringkatan skor di berbagai threshold; tidak perlu mengganti skor dengan kelas hasil threshold.</p><p>coords(r, \"best\", ...) secara default memilih threshold berdasarkan indeks Youden. Ketika r dibuat dari label test, threshold dipilih menggunakan test. Itu adalah tuning aturan keputusan, meskipun struktur tree tidak berubah. Pilih threshold dari validasi internal atau prediksi out-of-fold yang sesuai, lalu kunci sebelum evaluasi test.</p><p>caret::confusionMatrix membutuhkan data = prediksi dan reference = aktual. Menukar argumen mentransposisi matriks: accuracy tetap, tetapi ukuran seperti sensitivity dan precision berubah makna. positive = \"Yes\" menetapkan kelas positif dan tidak membetulkan argumen yang terbalik. Jika test sudah dipakai memilih threshold dan klaim final baru diperlukan, gunakan holdout baru atau evaluasi eksternal.</p><p><strong>Mengapa setiap opsi benar atau salah</strong></p><p class=\"ox\"><b>A</b> Memperbaiki argumen memang perlu, tetapi kebocoran pemilihan threshold pada test masih tersisa.</p><p class=\"ox\"><b>B</b> Kelas diskret menghilangkan informasi pemeringkatan skor untuk ROC penuh. Argumen confusionMatrix juga masih terbalik.</p><p class=\"ox\"><b>C</b> Benar. Memisahkan tuning threshold, mempertahankan skor untuk ROC, dan memperbaiki orientasi confusion matrix.</p><p class=\"ox\"><b>D</b> Arah \">\" tidak sesuai arti skor Yes pada soal. positive tidak menggantikan fungsi argumen reference.</p><p class=\"ox\"><b>E</b> Threshold adalah bagian dari aturan keputusan yang di-tune. Test tidak harus melatih tree agar dapat menyebabkan bias seleksi.</p><p><strong>Contoh perbaikan minimal</strong></p><pre class=\"r\"># p_valid dan y_valid berasal dari validasi internal\nr_valid = roc(y_valid, p_valid,\n  levels = c(\"No\", \"Yes\"), direction = \"&lt;\")\nb = coords(r_valid, \"best\", ret = \"threshold\",\n  transpose = FALSE)$threshold[1]\n# Setelah b dikunci, evaluasi pada test yang belum dipakai\np = predict(tree_final, test, type = \"prob\")[, \"Yes\"]\npred = factor(ifelse(p &gt;= b, \"Yes\", \"No\"),\n  levels = c(\"No\", \"Yes\"))\ncm = confusionMatrix(pred, test$Purchase, positive = \"Yes\")</pre>"
  ];

/** Dibuka saat halaman tes dimuat (pemanasan server); bisa juga dibuka di browser untuk cek versi. */
function doGet() {
  return out({ ok: true, ver: VER, pesan: "API Pretest/Post-test Pekan 4 Day 2 · Decision Tree aktif." });
}

function doPost(e) {
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(20000);
    const d = JSON.parse(e.postData.contents);
    const test = d.test === "posttest" ? "posttest" : "pretest";
    const ans = (d.answers || []).slice(0, KEY.length).map(a => String(a || "").toUpperCase());
    let correct = 0;
    KEY.forEach((k, i) => { if (ans[i] === k) correct++; });
    const score = Math.round(correct / KEY.length * 1000) / 10;
    const nama = String(d.nama || "").trim();
    const email = String(d.email || "").trim().toLowerCase();
    const now = new Date();

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const name = PREFIX + (test === "pretest" ? "Pretest" : "Posttest");
    let sh = ss.getSheetByName(name);
    if (!sh) {
      sh = ss.insertSheet(name);
      const head = ["Waktu", "Nama", "Email", "Benar", "Skor"];
      for (let i = 1; i <= KEY.length; i++) head.push("No " + i);
      sh.appendRow(head);
      sh.setFrozenRows(1);
    }
    sh.appendRow([now, nama, email, correct, score].concat(ans));
    upsertRekap_(ss, test, nama, email, score, now);

    const res = { ok: true, ver: VER, correct: correct, total: KEY.length, score: score };
    if (test === "posttest") { res.key = KEY; res.expl = EXPL; }
    return out(res);
  } catch (err) {
    return out({ ok: false, error: String(err) });
  } finally {
    lock.releaseLock();
  }
}

/**
 * Sheet Rekap: satu baris per email, berisi skor pretest & post-test terakhir dan kenaikannya.
 * Jika peserta mengirim lebih dari sekali, nilai yang tercatat di Rekap adalah kiriman terakhir
 * (semua kiriman tetap tersimpan lengkap di sheet Pretest / Posttest).
 */
function upsertRekap_(ss, test, nama, email, score, when) {
  const name = PREFIX + "Rekap";
  let sh = ss.getSheetByName(name);
  if (!sh) {
    sh = ss.insertSheet(name);
    sh.appendRow(["Email", "Nama", "Skor Pretest", "Waktu Pretest", "Skor Posttest", "Waktu Posttest", "Kenaikan (Post − Pre)"]);
    sh.setFrozenRows(1);
  }
  const last = sh.getLastRow();
  let row = -1;
  if (last > 1) {
    const emails = sh.getRange(2, 1, last - 1, 1).getValues();
    for (let i = 0; i < emails.length; i++) {
      if (String(emails[i][0]).trim().toLowerCase() === email) { row = i + 2; break; }
    }
  }
  if (row < 0) row = last + 1;
  sh.getRange(row, 1, 1, 2).setValues([[email, nama]]);
  sh.getRange(row, test === "pretest" ? 3 : 5, 1, 2).setValues([[score, when]]);
  sh.getRange(row, 7).setFormula(`=IF(AND(ISNUMBER(C${row}),ISNUMBER(E${row})),E${row}-C${row},"")`);
}

/**
 * Opsional: jalankan manual dari editor Apps Script untuk menyusun ulang sheet Rekap
 * dari isi sheet Pretest dan Posttest (misalnya setelah ada baris yang dihapus).
 */
function susunUlangRekap() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const old = ss.getSheetByName(PREFIX + "Rekap");
  if (old) ss.deleteSheet(old);
  ["pretest", "posttest"].forEach(test => {
    const sh = ss.getSheetByName(PREFIX + (test === "pretest" ? "Pretest" : "Posttest"));
    if (!sh || sh.getLastRow() < 2) return;
    sh.getRange(2, 1, sh.getLastRow() - 1, 5).getValues().forEach(r => {
      upsertRekap_(ss, test, r[1], String(r[2]).trim().toLowerCase(), r[4], r[0]);
    });
  });
}

function out(o) {
  return ContentService.createTextOutput(JSON.stringify(o))
    .setMimeType(ContentService.MimeType.JSON);
}
